### PR TITLE
fix: expected the module specifier to be a string literal

### LINKED ISSUE #32: bug: Expected the module specifier to be a string literal.
### Prerequisites

- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-angular-standalone-codemods) that already report this problem, without success.

### Codemod version

0.0.7

### Current Behavior

Run the codemod against my project and it fails half way through with the error `Expected the module specifier to be a string literal.`

### Expected Behavior

The codemod successfully runs without error.

If the codemod does error, it should attempt to print the source file path that cause the error so the user can attempt to manually resolve the issue and run the codemod again.

### Steps to Reproduce

1. Run codemod against my project 

### Code Reproduction URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by luke-rogers**
fixes #32

For some reason `project.getSourceFiles()` was returning html files causing `sourceFile.getImportDeclarations();` to fall over. I've also included printing the stack trace rather than just the error message to give the errors slightly more clarity.

### CODE REVIEW

File: packages/cli/src/angular/migrations/standalone/0004-migrate-import-statements.ts [hunk 1]
```diff
@@ -10,6 +10,10 @@ export const migrateImportStatements = async (
 ) => {
   // Get all typescript source files in the project and update any @ionic/angular imports to @ionic/angular/standalone
   for (const sourceFile of project.getSourceFiles()) {
+    if (sourceFile.getFilePath().endsWith(".html")) {
```
Comment (sean-perkins) [inline packages/cli/src/angular/migrations/standalone/0004-migrate-import-statements.ts:13]: Can we exclusively limit this to `.ts` extensions? While the intent is these should only be typescript files, we load additional file types into the project instance to be able to leverage the same API for migrations to HTML files in earlier migration steps. 

Thinking something like:
```ts
if (!sourceFile.getFilePath().endsWith(".ts")) {
  continue;
}
```

Comment (luke-rogers) [reply packages/cli/src/angular/migrations/standalone/0004-migrate-import-statements.ts]: Agree, made that change.

**Comment by sean-perkins** [comment]
Hey @luke-rogers ! Apologies this has been delayed. I'll get this rebased and into the v0.2.0 release today.
